# 00. TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

2. Find the shape, rank and size of the tensors you created in 1.

3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

4. Multiply the two tensors you created in 3 using matrix multiplication.

5. Multiply the two tensors you created in 3 using dot product.

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

7. Find the min and max values of the tensor you created in 6 along the first axis.

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

10. One-hot encode the tensor you created in 9.

## 1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [55]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.16.2


In [56]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [57]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [58]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [59]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

## 2. Find the shape, rank and size of the tensors you created in 1.

In [60]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([3, 2, 3]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=18>)

## 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [61]:
tf.random.set_seed(42)
tensor_A = tf.random.uniform(shape=(5, 300),
                             minval=0.0,
                             maxval=1.0)
tensor_B = tf.random.uniform(shape=(5, 300),
                             minval=0.0,
                             maxval=1.0)
tensor_A, tensor_B

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

## 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [62]:
tensor_A.shape, tensor_B.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

In [63]:
tensor_C = tf.matmul(tensor_A, tf.transpose(tensor_B))
tensor_C

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.159615, 73.98368 , 80.900536],
       [75.14636 , 68.80437 , 74.24303 , 71.84183 , 75.602066],
       [79.7594  , 75.64456 , 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05668 ],
       [85.056885, 74.26628 , 78.00686 , 74.886795, 83.13418 ]],
      dtype=float32)>

## 5. Multiply the two tensors you created in 3 using dot product.

In [64]:
tensor_D = tf.tensordot(tensor_A, tf.transpose(tensor_B), axes=1)
tensor_D

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.159615, 73.98368 , 80.900536],
       [75.14636 , 68.80437 , 74.24303 , 71.84183 , 75.602066],
       [79.7594  , 75.64456 , 77.797585, 74.74873 , 80.559845],
       [75.08526 , 69.064064, 74.30776 , 72.27616 , 76.05668 ],
       [85.056885, 74.26628 , 78.00686 , 74.886795, 83.13418 ]],
      dtype=float32)>

In [65]:
tensor_C == tensor_D

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])>

## 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [66]:
tf.random.set_seed(42)
tensor_E = tf.random.uniform(shape=(224, 224, 3),
                             minval=0.0,
                             maxval=1.0)
tensor_E.shape

TensorShape([224, 224, 3])

## 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [67]:
# Max val
tf.reduce_max(tensor_E)

<tf.Tensor: shape=(), dtype=float32, numpy=0.999998>

In [68]:
# Min val
tf.reduce_min(tensor_E)

<tf.Tensor: shape=(), dtype=float32, numpy=3.5762787e-07>

## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [69]:
tensor_F = tf.random.uniform(shape=[1, 224, 224, 3])
tensor_F.shape

TensorShape([1, 224, 224, 3])

In [70]:
tf.squeeze(tensor_F).shape

TensorShape([224, 224, 3])

## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [71]:
tensor_G = tf.random.uniform(shape=[10], minval=1, maxval=10)
tensor_G, tensor_G.shape

(<tf.Tensor: shape=(10,), dtype=float32, numpy=
 array([7.6723104, 6.656916 , 1.1564618, 4.088304 , 5.595739 , 4.399787 ,
        1.6589437, 1.1923326, 3.5845938, 5.2395544], dtype=float32)>,
 TensorShape([10]))

In [72]:
tf.argmax(tensor_G)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

## 10. One-hot encode the tensor you created in 9.

In [73]:
tf.one_hot(tf.cast(tensor_G, dtype=tf.int32), depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>